#!/usr/bin/env bash --posix
USAGE_MARKDOWN=../USAGE.md

function append {
  echo "$@" >> $USAGE_MARKDOWN
}

function addUsage {
  local command="$@"
  append
  append "## ck $command"
  append '```'
  append "$(../ck -h $@ 2>&1)"
  append '```'
  append "<sup><sub>[🔝 Back to top](#usage)</sub></sup>"
}

echo "<!-- Generated by dev/generateUsage.sh; DO NOT EDIT -->" > $USAGE_MARKDOWN
append "# Usage" 
append "### Index"
append "* [ck](#ck)"

SUBCOMMANDS=$(ls ../subcommands)
for subcommand in $SUBCOMMANDS
do
  name=$(basename $subcommand .sh)
  append "  * [${name}](#ck-${name})" 
done

append "### Commands"

addUsage

SUBCOMMANDS=$(ls ../subcommands)
for subcommand in $SUBCOMMANDS
do
  addUsage $(basename $subcommand .sh)
done
